site_name: Nuestro primer sitio MkDocs

site_url: https://ana-deb739.github.io/actividad22_3_AEG/
#site_dir: /docs
#docs_dir: /paginas
theme: readthedocs

nav:
 - Home: index.md
 - Hugo-Ananke: Edgar.md
 - Hugo-Papermod: German.md
 - Mkdocs-readthedocs: Ana.md

